version: "3.8"

services:
  php:
    build:
      context: .
      target: php
      args: 
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - balaman

  database:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - balaman

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www:delegated
      - ./nginx/:/etc/nginx/conf.d:delegated
      - ./nginx/vhosts:/etc/nginx/vhosts:delegated
      - ./nginx/logs:/var/log/nginx:delegated
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - php
    networks:
      - balaman
    ports:
      - "8081:80"
      - "8443:443"
            
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
    networks:
      - balaman

volumes:
  db-data:

networks:
  balaman:
