version: '3.7'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  database:
    environment:
      # Added replication and WAL level settings directly; ensure these don't conflict with your .env variables
      REPLICATION: 'true'
      WAL_LEVEL: 'logical'

  redis:
    ports:
      - "6379:6379"
