version: '3.7'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
  postgres:
    environment:
      REPLICATION: 'true'
      WAL_LEVEL: 'logical'
  redis:
    ports:
      - 6379:6379
