<?php

return [
    'nutrient_names' => [
        'water', 'protein', 'fat', 'carbohydrate', 'fiber',
        'vitaminA', 'vitaminD', 'vitaminE', 'vitaminK',
        'vitaminB1', 'vitaminB2', 'vitaminB3', 'vitaminB5',
        'vitaminB6', 'vitaminB7', 'vitaminB9', 'vitaminB12',
        'vitaminC', 
        'potassium', 'calcium', 'magnesium',
        'phosphorus', 'iron', 'zinc', 'copper', 'iodine', 'sodium',
    ],
    'nutrient_mesurement_units' => [
        'water' => 'l',
        'protein' => 'g',
        'fat' => 'g',
        'carbohydrate' => 'g',
        'fiber' => 'g',
        'vitaminA' => 'µg',
        'vitaminD' => 'µg',
        'vitaminE' => 'mg',
        'vitaminK' => 'µg',
        'vitaminB1' => 'mg',
        'vitaminB2' => 'mg',
        'vitaminB3' => 'mg',
        'vitaminB5' => 'mg',
        'vitaminB6' => 'mg',
        'vitaminB7' => 'µg',
        'vitaminB9' => 'µg',
        'vitaminB12' => 'µg',
        'vitaminC' => 'mg',
        'potassium' => 'mg',
        'calcium' => 'mg',
        'magnesium' => 'mg',
        'phosphorus' => 'mg',
        'iron' => 'mg',
        'zinc' => 'mg',
        'copper' => 'µg',
        'iodine' => 'µg',
        'sodium' => 'g',
    ],
];
